Solution controller
FrediKats/AssignmentManager pull request #23
Opened 2021-06-22 20:20 UTC by Erartria

2021-06-24 17:44 UTC, s4xack approved these changes

2021-06-24 17:44 UTC, s4xack commented on AssignmentManager/Server/Controllers/InstructorSubjectsController.cs
> +    public class InstructorSubjectsController : ControllerBase
InstructoSubject - промежуточная сущность для Many2Many между Instructor и Subject, это не является какой-то единицец БЛ приложения, и не должно быть никаких возможностей работы с ним

2021-06-24 17:44 UTC, s4xack commented on AssignmentManager/Server/Controllers/InstructorsController.cs
> +        public async Task<IActionResult> PostAsync([FromBody] SaveInstructorResource resource)
1. Про суффикс Async уже писал в другом пр
2. Нейминг методов

2021-06-24 17:44 UTC, s4xack commented on AssignmentManager/Server/Extensions/StringExtensions.cs
> +        public static DateTime ParseToProjectTime(this string parsingSting)
asp сам у меет мапить строки в DateTime в принимаемых моделях

2021-06-24 17:44 UTC, s4xack commented on AssignmentManager/Server/Mapping/ResourceToModelProfiler.cs
> -            CreateMap<SaveGroupResource, Group>();
а вот это точно должно было выпилиться, или это последствия неудачного мерджа

2021-06-24 17:44 UTC, s4xack commented on AssignmentManager/Server/Models/Assignment.cs
> +                Subject = new Subject(),
нарушается консистентность

2021-06-24 17:44 UTC, s4xack commented on AssignmentManager/Server/Models/Assignment.cs
> +        public static implicit operator Assignment(SaveAssignmentResource assignmentResource)
а зачем везде имплисит касты при том, что у везде юзаются автомапер

2021-06-24 17:44 UTC, s4xack commented on AssignmentManager/Server/Models/Instructor.cs
> +        /*[Key] public int IsuId { get; set; }
закомментированный код?

2021-06-24 17:44 UTC, s4xack commented on AssignmentManager/Server/Models/Group.cs
>          [Required] public Speciality Speciality { get; set; }
не пихайте в одну строку атрибут и пропертю

2021-06-24 17:44 UTC, s4xack commented on AssignmentManager/Server/Models/Solution.cs
>          [Key] public int SolutionId { get; set; }
Достаточно просто Id без приставки Solution

2021-06-24 17:44 UTC, s4xack commented on AssignmentManager/Server/Models/Speciality.cs
>          [Required] public EStudyType EnumStudyType { get; set; }
Приставка E/Enum - ненужный мусор, ide уже умееют в хайлайт кода и аннотации

2021-06-24 17:44 UTC, s4xack commented on AssignmentManager/Server/Models/Speciality.cs
> +                byteStudyType = (EStudyType) specialityResource.EnumStudyType;
касты енамов - что-то очень плохое

2021-06-24 17:44 UTC, s4xack commented on AssignmentManager/Server/Models/Speciality.cs
> +            catch (Exception)
никогда не надо хендлить Exception
нужно хендлить явно ту ошибку, которая здесь ожидаема

2021-06-24 17:44 UTC, s4xack commented on AssignmentManager/Server/Services/Communication/InstructorResponse.cs
> +    public class InstructorResponse : BaseResponse
в прошлом ревью уже писал про подобное решение с респонсами

2021-06-24 17:44 UTC, s4xack commented on AssignmentManager/Server/Services/IAssignmentService.cs
> +        Task<Assignment> Update(int id, SaveAssignmentResource item);
почему id отдельно принимается?

2021-06-24 17:44 UTC, s4xack commented on AssignmentManager/Server/Services/IInstructorService.cs
> +        Task<InstructorResponse> SaveAsync(Instructor instructor);
тут должен быть Create/Add/Insert, но точно не Save

2021-06-24 17:44 UTC, s4xack commented on AssignmentManager/Server/Services/InstructorService.cs
> +            }
вот так вот делать не нужно в EF есть Include, с помощью которого можно доставать связные сущности

2021-06-24 17:44 UTC, s4xack commented on AssignmentManager/Server/Services/SpecialityService.cs
>          private string GetAllEnumValues<T>(T enumType) where T : Type
такие вещи делать не нужно
контроллеры хорошо принимают енамы и сами скажут об ошипке мапинга

2021-06-24 17:45 UTC, s4xack requested changes
упс

2021-06-26 09:27 UTC, Erartria commented on AssignmentManager/Server/Models/Assignment.cs
> +        public static implicit operator Assignment(SaveAssignmentResource assignmentResource)
Не везде, я забыл их из Mapping-ов выпилить.

2021-06-26 09:29 UTC, Erartria commented on AssignmentManager/Server/Services/IAssignmentService.cs
> +        Task<Assignment> Update(int id, SaveAssignmentResource item);
Я немного не понял, ты имеешь ввиду эту строку? Task<Assignment> GetById(int id) - по id я вывожу связные сущности

2021-06-26 10:35 UTC, s4xack commented on AssignmentManager/Server/Services/IAssignmentService.cs
> +        Task<Assignment> Update(int id, SaveAssignmentResource item);
Я про строку Update
Зачем отдельно принимается Id и сущность, которая и содержит данный id

2021-06-26 15:21 UTC, Erartria commented on AssignmentManager/Server/AssignmentManager.Server.csproj
> +    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="5.0.5" />
Убрал : fix: remove repeated dependence for EntityFrameworkCore.InMemory

2021-06-26 15:23 UTC, Erartria commented on AssignmentManager/Server/Controllers/AssignmentsController.cs
> +        public async Task<IActionResult> GetAssignmentByIdCompletely(int id)
Переделал для модулей: Solution-Assignment-Student-Group-Speciality : fix: add middleware & change responses to ActionResult<Entity>

2021-06-26 15:24 UTC, Erartria commented on AssignmentManager/Server/Controllers/AssignmentsController.cs
> +            catch (Exception ex)
Написал middleware (CustomErrorHandlerMiddleware) : fix: add middleware & change responses to ActionResult

2021-06-26 15:24 UTC, Erartria commented on AssignmentManager/Server/Controllers/AssignmentsController.cs
> +            if (!ModelState.IsValid)
Действительно без нее все ок

2021-06-26 15:25 UTC, Erartria commented on AssignmentManager/Server/Controllers/GroupsController.cs
> +        public async Task<ActionResult> GetGroupByIdCompletely(int id)
Переделал для модулей: Solution-Assignment-Student-Group-Speciality : fix: add middleware & change responses to ActionResult

2021-06-26 15:26 UTC, Erartria commented on AssignmentManager/Server/Mapping/ResourceToModelProfiler.cs
> -            CreateMap<SaveGroupResource, Group>();
Удалил для модулей: Solution-Assignment-Student-Group-Speciality, т.к. использую неявный конструктор

2021-06-26 15:28 UTC, Erartria commented on AssignmentManager/Server/Models/Assignment.cs
> +                Subject = new Subject(),
Нужно Subject = new Subject(), удалить или что? Я немного не понял. Или для subjects-instructors так же сделать?

2021-06-26 15:30 UTC, Erartria commented on AssignmentManager/Server/Models/Speciality.cs
> +            catch (Exception)
Написал Middleware и для сервисов ошибки нормальные (вроде) поставил

2021-06-26 15:36 UTC, Erartria commented on AssignmentManager/Server/Services/IAssignmentService.cs
> +        Task<Assignment> Update(int id, SaveAssignmentResource item);
SaveAssignmentResource его не содержит. Вот класс: 
```CSharp
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace AssignmentManager.Shared
{
    public class SaveAssignmentResource
    {
        [Required] public string Name { get; set; }
        [Required] public string Description { get; set; }
        [Required] public string Deadline { get; set; }
        
        public int SubjectId { get; set; }
    }
}
```
Для PUT пишу так: {server}/api/assignments/{id}
и тело:
```JSon
{
    "name": "Test",
    "description": "Pisat` i eshe ras risat`.",
    "deadline": "2020-12-12 00:00",
    "subjectId": 100
}
```

2021-06-26 15:41 UTC, Erartria commented on AssignmentManager/Server/Controllers/AssignmentsController.cs
> +        public async Task<IReadOnlyCollection<AssignmentResourceBriefly>> GetAllAssignmentsBriefly()
Нашел. Ты там писал: "Если где-то нужно вернуть коллекцию то лучше использовать IReadonlyCollection." https://github.com/FrediKats/AssignmentManager/pull/9#discussion_r650117738

2021-06-26 15:45 UTC, Erartria commented on AssignmentManager/Server/Models/Speciality.cs
> +            catch (Exception)
Правда на счет самого текста ошибок не уверен. Я там к MethodBase.GetCurrentMethod().ReflectedType?.Name обращаюсь, что бы указать из какой функции (Create, Get, Update и т.д.) ошибка вылетает

2021-06-26 15:48 UTC, Erartria commented on AssignmentManager/Server/Services/SpecialityService.cs
>          private string GetAllEnumValues<T>(T enumType) where T : Type
Что-то типо такого нужно использовать?
services.AddMvc().AddJsonOptions(options =>
    {
      options.SerializerSettings.Converters.Add(new Newtonsoft.Json.Converters.StringEnumConverter());
      options.SerializerSettings.NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore;
    });

2021-06-26 17:22 UTC, merged

2021-06-28 11:36 UTC, hatulmadan1 commented on AssignmentManager/Server/Models/Group.cs
>          [Required] public Speciality Speciality { get; set; }
Исправлено во всех файлах модели

2021-06-28 11:40 UTC, hatulmadan1 commented on AssignmentManager/Server/Services/IInstructorService.cs
> +        Task<InstructorResponse> SaveAsync(Instructor instructor);
Исправлено в этом и нескольких других случаях на Add

2021-06-28 14:10 UTC, hatulmadan1 commented on AssignmentManager/Server/Services/Communication/InstructorResponse.cs
> +    public class InstructorResponse : BaseResponse
Исправлено, Response'ы удалены

2021-06-28 14:34 UTC, hatulmadan1 commented on AssignmentManager/Server/Controllers/InstructorsController.cs
> +        public async Task<IActionResult> PostAsync([FromBody] SaveInstructorResource resource)
Это было ревью кода другого человека, сори
Пофикшено.

2021-06-28 21:24 UTC, Erartria commented on AssignmentManager/Server/Controllers/AssignmentsController.cs
> +            if (!ModelState.IsValid)
Что бы оно работало коректно нужно [ApiController] над контроллером объявить. Без это валидация nullable типов не работает, а если их в SaveResource не использовать - то и без нотации работает